name: barloon_app
description: barloon-menu-flutter-web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'
dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase_core: any
  cupertino_icons: any
  url_launcher: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    path: ../packages/flutter_web
  flutter_web_ui:
    path: ../packages/flutter_web_ui
